name: Lint, Check, and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-check-test:
    name: Luacheck, Stylua, and Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: v0.5.0

    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1.5"

    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: Run luacheck
      run: |
        luarocks install luacheck
        luacheck .

    - name: Run stylua --check
    - uses: actions/checkout@v2
    - uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .
        version: 0.10.1

    - name: Run tests
      run: make test

    - name: Check Rust build
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
      run: |
        make build-rust
        git diff --exit-code bin/dash-nvim # checks that binary is up to date
