name: Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-check-test:
    name: Luacheck, Stylua, and Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: nightly

    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1.5"

    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: Run stylua
      run: |
        luarocks install luacheck
        luacheck .

    - name: Run luacheck
    - uses: actions/checkout@v2
    - uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .
        version: 0.10.1

    - name: Run tests
      run: make test
